name: "Check if the code pass unit test!"

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  run-test:
    name: Ping someone in the comment section of PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo on to a job runner.
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # Checkout this repository

      - name: Set up Python 3.8
        uses: actions/setup-python@41b7212b1668f5de9d65e9c82aa777e6bbedb3a8
        with:
          python-version: 3.8

      - name: Log into AWS (DO NOT USE THIS, THIS IS FOR DEMO ONLY)
        run: |
          run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY}}" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN}}" >> $GITHUB_ENV
          echo Sign in using AWS_ACCESS_KEY_ID - ${{ secrets.AWS_ACCESS_KEY_ID }}
          echo Sign in using AWS_SECRET_ACCESS_KEY - ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          echo Sign in using AWS_SESSION_TOKEN - ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Log into FACEBOOK (DO NOT USE THIS, THIS IS FOR DEMO ONLY)
        run: |
          run: |
          echo "FACEBOOK_USER_NAME=${{ secrets.FACEBOOK_USER_NAME }}" >> $GITHUB_ENV
          echo "FACEBOOK_PASSWORD=${{ secrets.FACEBOOK_PASSWORD}}" >> $GITHUB_ENV
          echo Sign in using FACEBOOK_USER_NAME - ${{ secrets.FACEBOOK_USER_NAME }}
          echo Sign in using FACEBOOK_PASSWORD - ${{ secrets.FACEBOOK_PASSWORD }}

      - name: Run unit tests
        run: |
          python -m unittest -v

      - uses: schoi-godaddy/ping-reviewer-aksion@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          who-to-ping: "schoi-godaddy"
